[pytest]
testpaths = test_cases
python_files = test_*.py
python_functions = test_*
markers =
    smoke: core smoke test cases
    regression: regression test cases
    negative: negative test cases
    flow: api flow test cases
    auth: authentication test cases
    headers: headers test cases
    session: session and cookie test cases
    retry: retry request test cases
    api_db: api response and database validation test cases
    ui: selenium ui test cases

disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True

