[pytest]
testpaths = test_cases
python_files = test_*.py
python_functions = test_*
python_classes = Test*
markers =
    smoke: 核心冒烟测试
    regression: 回归测试
    negative: 异常场景测试
    flow: 接口流程测试
    auth: Bearer Token 鉴权测试
    headers: 请求头测试
    session: Session 与 Cookie 测试
    retry: 请求重试测试
    api_db: 接口与数据库联合校验
    api_mysql: 接口与 MySQL 数据库联合校验
    ui: Selenium Ui 自动化测试

disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True

